In [25]:
import pandas as pd
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score 
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import LabelEncoder

# Bank Reserves

In [56]:
br_labels = pd.read_csv("C:/Users/met48/Desktop/TS-Clustering/bank_reserves_results.csv")
br_inputs = pd.read_csv("C:/Users/met48/Desktop/TS-Clustering/SimData/bank_reserves_inputs.csv", header=None)

In [57]:
br_labels = br_labels.set_index("Unnamed: 0")
br_labels = br_labels.transpose()
br_labels.index.name = None
br_labels = br_labels.rename_axis(None, axis=1)
br_labels.index = br_labels.index.astype(int)
df = pd.merge(br_inputs, br_labels, left_index=True, right_index=True)
df

In [71]:
def knn_br_method(method):
    X_train, X_test, y_train, y_test = train_test_split(df[0].values.reshape(-1, 1), df[method], test_size=0.1, random_state = 1)

    knn_clf=KNeighborsClassifier()
    knn_clf.fit(X_train,y_train)
    ypred=knn_clf.predict(X_test)

    result = confusion_matrix(y_test, ypred)
    print("Confusion Matrix:")
    print(result)
    report = classification_report(y_test, ypred)
    print("Report:",)
    print (report)
    acc = accuracy_score(y_test,ypred)
    print("Accuracy:",acc)

In [72]:
knn_br_method('PCA_KMeans')

Confusion Matrix:
[[ 597    0   74   68    0    0    0]
 [   1 1439    0  358   85  167    0]
 [  82    0 1179    0    0    0  127]
 [  67  634    0  408   41   62    0]
 [   0  390    0   67   14   42    0]
 [   0  554    0  119   36   67    0]
 [   0    1  115    0    0    0 3206]]
Report:
              precision    recall  f1-score   support

           0       0.80      0.81      0.80       739
           1       0.48      0.70      0.57      2050
           2       0.86      0.85      0.86      1388
           3       0.40      0.34      0.37      1212
           4       0.08      0.03      0.04       513
           5       0.20      0.09      0.12       776
           6       0.96      0.97      0.96      3322

    accuracy                           0.69     10000
   macro avg       0.54      0.54      0.53     10000
weighted avg       0.66      0.69      0.67     10000

Accuracy: 0.691

In [73]:
knn_br_method('DAE_KMeans')

Confusion Matrix:
[[ 574    0    0   65    0    0   51]
 [   0 2842    0    0  296    0    0]
 [   0    0 1938    0    0  105    0]
 [  71    0    0  538   56    0    0]
 [   0  839    0   60  498    0    0]
 [   0    0   97    0    0 1039   64]
 [  63    0    0    0    0   73  731]]
Report:
              precision    recall  f1-score   support

           0       0.81      0.83      0.82       690
           1       0.77      0.91      0.83      3138
           2       0.95      0.95      0.95      2043
           3       0.81      0.81      0.81       665
           4       0.59      0.36      0.44      1397
           5       0.85      0.87      0.86      1200
           6       0.86      0.84      0.85       867

    accuracy                           0.82     10000
   macro avg       0.81      0.79      0.80     10000
weighted avg       0.81      0.82      0.81     10000

Accuracy: 0.816

In [74]:
knn_br_method('DCAE_KMeans')

Confusion Matrix:
[[ 740    0    0    0    0   55   56]
 [   0  848    0    0 1089    0   39]
 [   0    0 1046   63    0   79    0]
 [   0    0   78 1931    0    0    0]
 [   0  930    0    0 1244    0   34]
 [  55    0   60    0    0  754    0]
 [  54   48    0    0   27    0  770]]
Report:
              precision    recall  f1-score   support

           0       0.87      0.87      0.87       851
           1       0.46      0.43      0.45      1976
           2       0.88      0.88      0.88      1188
           3       0.97      0.96      0.96      2009
           4       0.53      0.56      0.54      2208
           5       0.85      0.87      0.86       869
           6       0.86      0.86      0.86       899

    accuracy                           0.73     10000
   macro avg       0.77      0.78      0.77     10000
weighted avg       0.73      0.73      0.73     10000

Accuracy: 0.7333

In [75]:
knn_br_method('PCA_Agglom')

Confusion Matrix:
[[2221  310   66    0    0   46    0]
 [ 876  124    3    0    0   19    0]
 [ 114   11  452   56    0    2    0]
 [   0    0   66  739    0    0   87]
 [   0    0    0    0 2965    0  116]
 [ 439   66    1    0    0    8    0]
 [   0    0    0  100  120    0  993]]
Report:
              precision    recall  f1-score   support

           0       0.61      0.84      0.71      2643
           1       0.24      0.12      0.16      1022
           2       0.77      0.71      0.74       635
           3       0.83      0.83      0.83       892
           4       0.96      0.96      0.96      3081
           5       0.11      0.02      0.03       514
           6       0.83      0.82      0.82      1213

    accuracy                           0.75     10000
   macro avg       0.62      0.61      0.61     10000
weighted avg       0.71      0.75      0.72     10000

Accuracy: 0.7502

In [76]:
knn_br_method('DAE_Agglom')

Confusion Matrix:
[[ 752    0    0   50   62    0   14]
 [   0 1277   65    0    0   98    0]
 [   0   70  765    0   63    0    0]
 [  55    0    0  772    0    0 1060]
 [  58    0   51    0  549    0    0]
 [   0  100    0    0    0 1755    0]
 [   1    0    0  769    0    0 1614]]
Report:
              precision    recall  f1-score   support

           0       0.87      0.86      0.86       878
           1       0.88      0.89      0.88      1440
           2       0.87      0.85      0.86       898
           3       0.49      0.41      0.44      1887
           4       0.81      0.83      0.82       658
           5       0.95      0.95      0.95      1855
           6       0.60      0.68      0.64      2384

    accuracy                           0.75     10000
   macro avg       0.78      0.78      0.78     10000
weighted avg       0.75      0.75      0.75     10000

Accuracy: 0.7484

In [77]:
knn_br_method('DCAE_Agglom')

Confusion Matrix:
[[2643    0    0    0   87    0    0]
 [   0 1056    0   73   76    0    0]
 [   0    0  606    5    0  354  368]
 [   0   89    3  752    0   42   15]
 [ 103   58    0    0  722    0    0]
 [   0    0  510   70    0  420  376]
 [   0    0  658   61    0  421  432]]
Report:
              precision    recall  f1-score   support

           0       0.96      0.97      0.97      2730
           1       0.88      0.88      0.88      1205
           2       0.34      0.45      0.39      1333
           3       0.78      0.83      0.81       901
           4       0.82      0.82      0.82       883
           5       0.34      0.31      0.32      1376
           6       0.36      0.27      0.31      1572

    accuracy                           0.66     10000
   macro avg       0.64      0.65      0.64     10000
weighted avg       0.66      0.66      0.66     10000

Accuracy: 0.6631

In [78]:
knn_br_method('PCA_Spectral')

Confusion Matrix:
[[1052    0    0  201    0    0    0]
 [   0   39  263    0    0  212    0]
 [   0  166  937    0    0  705    0]
 [ 242    0    0 1211    0    0  144]
 [   0    0    0    0  987   65   87]
 [   0  142  936    0   60 1168    0]
 [   0    0    0  120  104    0 1159]]
Report:
              precision    recall  f1-score   support

           0       0.81      0.84      0.83      1253
           1       0.11      0.08      0.09       514
           2       0.44      0.52      0.48      1808
           3       0.79      0.76      0.77      1597
           4       0.86      0.87      0.86      1139
           5       0.54      0.51      0.52      2306
           6       0.83      0.84      0.84      1383

    accuracy                           0.66     10000
   macro avg       0.63      0.63      0.63     10000
weighted avg       0.65      0.66      0.65     10000

Accuracy: 0.6553

In [79]:
knn_br_method('DAE_Spectral')

Confusion Matrix:
[[ 996    0    0    0  119    0    0]
 [   0  749  349  356    0    0   54]
 [   0  500  348  313    0    0    0]
 [   0  695  418  378    0    0    4]
 [ 130    0    0    0 1337   95    0]
 [   0    0    0    0   72 1486   65]
 [   0   71   19   18    0   56 1372]]
Report:
              precision    recall  f1-score   support

           0       0.88      0.89      0.89      1115
           1       0.37      0.50      0.43      1508
           2       0.31      0.30      0.30      1161
           3       0.35      0.25      0.30      1495
           4       0.88      0.86      0.87      1562
           5       0.91      0.92      0.91      1623
           6       0.92      0.89      0.91      1536

    accuracy                           0.67     10000
   macro avg       0.66      0.66      0.66     10000
weighted avg       0.67      0.67      0.66     10000

Accuracy: 0.6666

In [80]:
knn_br_method('DCAE_Spectral')

Confusion Matrix:
[[1495    0    0    0    0   93    0]
 [   0  970   30  300    0    0  472]
 [   0   28 1279    0   48    0   28]
 [   0  561    0  218    0    0  237]
 [   0    0   67    0 1052   63    0]
 [  93    0    0    0   67 1318    0]
 [   0  790   57  293    0    0  441]]
Report:
              precision    recall  f1-score   support

           0       0.94      0.94      0.94      1588
           1       0.41      0.55      0.47      1772
           2       0.89      0.92      0.91      1383
           3       0.27      0.21      0.24      1016
           4       0.90      0.89      0.90      1182
           5       0.89      0.89      0.89      1478
           6       0.37      0.28      0.32      1581

    accuracy                           0.68     10000
   macro avg       0.67      0.67      0.67     10000
weighted avg       0.67      0.68      0.67     10000

Accuracy: 0.6773

# Epstein

In [96]:
br_labels = pd.read_csv("C:/Users/met48/Desktop/TS-Clustering/epstein_results.csv")
br_inputs = pd.read_csv("C:/Users/met48/Desktop/TS-Clustering/SimData/epsteinCV_inputs.csv", header=None)

In [97]:
br_inputs[['num1', 'num2', 'num3']] = br_inputs[0].str.split(' ', expand=True).astype(float)
br_inputs = br_inputs.drop(columns=[0])
br_labels = br_labels.set_index("Unnamed: 0")
br_labels = br_labels.transpose()
br_labels.index.name = None
br_labels = br_labels.rename_axis(None, axis=1)
br_labels.index = br_labels.index.astype(int)
df = pd.merge(br_inputs, br_labels, left_index=True, right_index=True)
df

,num1,num2,num3,PCA_KMeans,DAE_KMeans,DCAE_KMeans,PCA_Agglom,DAE_Agglom,DCAE_Agglom,PCA_Spectral,DAE_Spectral,DCAE_Spectral
0,0.579364,0.362797,0.045004,3,4,6,1,4,0,2,5,7
1,0.905778,0.049225,0.769210,5,7,2,7,2,2,0,0,0
2,0.761473,0.167152,0.565592,5,7,2,3,2,2,0,1,6
3,0.979122,0.007172,0.161529,0,0,0,2,3,1,1,2,3
4,0.521911,0.427794,0.762568,5,7,2,7,2,2,7,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
50357,0.988652,0.004317,0.274946,0,0,0,2,3,1,1,2,3
50358,0.726030,0.203366,0.597790,5,7,2,7,2,2,0,1,6
50359,0.849297,0.057407,0.704192,5,7,2,7,2,2,0,0,0
50360,0.976113,0.002261,0.987066,5,7,2,7,2,2,5,6,5
50361,0.946500,0.014863,0.399148,0,0,0,2,3,1,1,2,3

In [106]:
def knn_epstein_method(method):
    X_train, X_test, y_train, y_test = train_test_split(df[['num1', 'num2', 'num3']].values, df[method], test_size=0.1, random_state = 1)

    knn_clf=KNeighborsClassifier()
    knn_clf.fit(X_train,y_train)
    ypred=knn_clf.predict(X_test)

    result = confusion_matrix(y_test, ypred)
    print("Confusion Matrix:")
    print(result)
    report = classification_report(y_test, ypred)
    print("Report:",)
    print (report)
    acc = accuracy_score(y_test,ypred)
    print("Accuracy:",acc)

In [107]:
knn_epstein_method('PCA_KMeans')

Confusion Matrix:
[[ 445    0    7    3   16    0    6    4]
 [   1 1055    0   67    0   68    4    0]
 [  12    1  132   30    9    0    0   12]
 [   8   84   25  693    0    1    4    0]
 [  40    0   13    2   41    0    0    5]
 [   2   56    0    1    0 2042    5    0]
 [  14    8    0    3    0   11   52    0]
 [   4    0   16    2   24    0    0    9]]
Report:
              precision    recall  f1-score   support

           0       0.85      0.93      0.88       481
           1       0.88      0.88      0.88      1195
           2       0.68      0.67      0.68       196
           3       0.87      0.85      0.86       815
           4       0.46      0.41      0.43       101
           5       0.96      0.97      0.97      2106
           6       0.73      0.59      0.65        88
           7       0.30      0.16      0.21        55

    accuracy                           0.89      5037
   macro avg       0.72      0.68      0.70      5037
weighted avg       0.88      0.89      0.88      5037

Accuracy: 0.8872344649593011

In [108]:
knn_epstein_method('DAE_KMeans')

Confusion Matrix:
[[ 401    4    3   29    0    6    2    6]
 [   3 1030   24    0   23    0    0   71]
 [   3   26  389   10   28    7   21    0]
 [  65    3    4   91    0    7   11    1]
 [   0   35   22    0  696    0    0    0]
 [  11    1   24   10    0   13    1    0]
 [   3    0   35   28    0    2   36    0]
 [   3   77    0    2    0    0    0 1770]]
Report:
              precision    recall  f1-score   support

           0       0.82      0.89      0.85       451
           1       0.88      0.89      0.89      1151
           2       0.78      0.80      0.79       484
           3       0.54      0.50      0.52       182
           4       0.93      0.92      0.93       753
           5       0.37      0.22      0.27        60
           6       0.51      0.35      0.41       104
           7       0.96      0.96      0.96      1852

    accuracy                           0.88      5037
   macro avg       0.72      0.69      0.70      5037
weighted avg       0.87      0.88      0.88      5037

Accuracy: 0.8786976374826285

In [109]:
knn_epstein_method('DCAE_KMeans')

Confusion Matrix:
[[ 488    0    0    4    4   15    0    8]
 [   0 1094   70   28    0    0   26    3]
 [   0   76 1789    2    0    0    0    8]
 [   6   34    1  375   17    7   16    7]
 [  20    0    0   50   13   15    0    0]
 [  39    0    0    8   11   30    0    0]
 [   0   36    0   15    0    0  628    0]
 [  14   10   10    3    0    1    0   56]]
Report:
              precision    recall  f1-score   support

           0       0.86      0.94      0.90       519
           1       0.88      0.90      0.89      1221
           2       0.96      0.95      0.96      1875
           3       0.77      0.81      0.79       463
           4       0.29      0.13      0.18        98
           5       0.44      0.34      0.38        88
           6       0.94      0.92      0.93       679
           7       0.68      0.60      0.64        94

    accuracy                           0.89      5037
   macro avg       0.73      0.70      0.71      5037
weighted avg       0.88      0.89      0.88      5037

Accuracy: 0.8880285884455033

In [110]:
knn_epstein_method('PCA_Agglom')

Confusion Matrix:
[[  70    8    5    0    0   28   14    0]
 [   9  965   12   61    1    1   17    0]
 [   5    8  429    2   11   19    0    0]
 [   0   60    5 1304    1    0    0   50]
 [   0    2   15    7   28    0    0    4]
 [  33    5   38    0    0   75    1    0]
 [  34   29    0    0    0    3   58    0]
 [   0    1    0   53    6    0    0 1560]]
Report:
              precision    recall  f1-score   support

           0       0.46      0.56      0.51       125
           1       0.90      0.91      0.90      1066
           2       0.85      0.91      0.88       474
           3       0.91      0.92      0.92      1420
           4       0.60      0.50      0.54        56
           5       0.60      0.49      0.54       152
           6       0.64      0.47      0.54       124
           7       0.97      0.96      0.96      1620

    accuracy                           0.89      5037
   macro avg       0.74      0.71      0.72      5037
weighted avg       0.89      0.89      0.89      5037

Accuracy: 0.8912050823903117

In [111]:
knn_epstein_method('DAE_Agglom')

Confusion Matrix:
[[ 128   13    2   46    0   10    5    5]
 [  23  512    1    2   24   17   10   32]
 [   1    1 1979    0    0    0    0   44]
 [  39    6    0  399    0    2    6    1]
 [   0   17    0    0  659    0    0   28]
 [  35   33    0    1    0   23    1    0]
 [  10   20    0    9    0    2   13    0]
 [   2   42   70    1   43    0    0  720]]
Report:
              precision    recall  f1-score   support

           0       0.54      0.61      0.57       209
           1       0.80      0.82      0.81       621
           2       0.96      0.98      0.97      2025
           3       0.87      0.88      0.88       453
           4       0.91      0.94      0.92       704
           5       0.43      0.25      0.31        93
           6       0.37      0.24      0.29        54
           7       0.87      0.82      0.84       878

    accuracy                           0.88      5037
   macro avg       0.72      0.69      0.70      5037
weighted avg       0.88      0.88      0.88      5037

Accuracy: 0.8800873535834822

In [112]:
knn_epstein_method('DCAE_Agglom')

Confusion Matrix:
[[ 853    1   31    0    0    0    0   30]
 [   1  499    1   16    3   21    1    1]
 [  40    5 2346    7    0    0    0   32]
 [   1   31   13   31    6    1    0    2]
 [   0   11    0   10  180   12    5   30]
 [   0   36    0    1    8   37    4    0]
 [   0    9    0    1   18   12    3    0]
 [  29    6   34    5   28    0    0  585]]
Report:
              precision    recall  f1-score   support

           0       0.92      0.93      0.93       915
           1       0.83      0.92      0.87       543
           2       0.97      0.97      0.97      2430
           3       0.44      0.36      0.40        85
           4       0.74      0.73      0.73       248
           5       0.45      0.43      0.44        86
           6       0.23      0.07      0.11        43
           7       0.86      0.85      0.86       687

    accuracy                           0.90      5037
   macro avg       0.68      0.66      0.66      5037
weighted avg       0.90      0.90      0.90      5037

Accuracy: 0.9001389716100854

In [113]:
knn_epstein_method('PCA_Spectral')

Confusion Matrix:
[[ 835    0    0    0    2    5   53   41]
 [   0  408    6   19   15    0    0    0]
 [   0    7  824   32   11    1   63    0]
 [   0   37   34  183    0    0    0    0]
 [   1   14    6    0  174    6    5    0]
 [   7    0    2    0   10  572    3   25]
 [  67    0   68    0    6    1 1042    0]
 [  38    0    0    0    0   20    0  394]]
Report:
              precision    recall  f1-score   support

           0       0.88      0.89      0.89       936
           1       0.88      0.91      0.89       448
           2       0.88      0.88      0.88       938
           3       0.78      0.72      0.75       254
           4       0.80      0.84      0.82       206
           5       0.95      0.92      0.93       619
           6       0.89      0.88      0.89      1184
           7       0.86      0.87      0.86       452

    accuracy                           0.88      5037
   macro avg       0.86      0.87      0.86      5037
weighted avg       0.88      0.88      0.88      5037

Accuracy: 0.8798888227119317

In [114]:
knn_epstein_method('DAE_Spectral')

Confusion Matrix:
[[430  36   0  22   1   0   2   0]
 [ 32 607   0   0  50   0   0   1]
 [  0   0 388   0   1   0   0  61]
 [ 27   0   0 225   0   0  15   0]
 [  2  64   1   0 834  25   0  31]
 [  0   0   0   0  34 641   0  19]
 [  0   2   0  20   0   0 547   1]
 [  0   7  62   0  31  20   0 798]]
Report:
              precision    recall  f1-score   support

           0       0.88      0.88      0.88       491
           1       0.85      0.88      0.86       690
           2       0.86      0.86      0.86       450
           3       0.84      0.84      0.84       267
           4       0.88      0.87      0.87       957
           5       0.93      0.92      0.93       694
           6       0.97      0.96      0.96       570
           7       0.88      0.87      0.87       918

    accuracy                           0.89      5037
   macro avg       0.89      0.89      0.89      5037
weighted avg       0.89      0.89      0.89      5037

Accuracy: 0.8874329958308517

In [115]:
knn_epstein_method('DCAE_Spectral')

Confusion Matrix:
[[427   0   5   0  19   1  45   0]
 [  0 522  16   0   0   0  34  32]
 [  2  15 818  56   0   1  33  18]
 [  0   0  54 588   0   0   1   0]
 [ 27   0   0   0 242  15   0   0]
 [  0   0   2   0  19 547   2   0]
 [ 38  38  31   0   0   0 853   0]
 [  0  38  19   0   0   0   0 479]]
Report:
              precision    recall  f1-score   support

           0       0.86      0.86      0.86       497
           1       0.85      0.86      0.86       604
           2       0.87      0.87      0.87       943
           3       0.91      0.91      0.91       643
           4       0.86      0.85      0.86       284
           5       0.97      0.96      0.96       570
           6       0.88      0.89      0.88       960
           7       0.91      0.89      0.90       536

    accuracy                           0.89      5037
   macro avg       0.89      0.89      0.89      5037
weighted avg       0.89      0.89      0.89      5037

Accuracy: 0.8886241810601548

# Forest Fires

In [116]:
br_labels = pd.read_csv("C:/Users/met48/Desktop/TS-Clustering/forestfire_results.csv")
br_inputs = pd.read_csv("C:/Users/met48/Desktop/TS-Clustering/SimData/forest_fire_inputs.csv", header=None)

In [117]:
br_labels = br_labels.set_index("Unnamed: 0")
br_labels = br_labels.transpose()
br_labels.index.name = None
br_labels = br_labels.rename_axis(None, axis=1)
br_labels.index = br_labels.index.astype(int)
df = pd.merge(br_inputs, br_labels, left_index=True, right_index=True)
df

,0,PCA_KMeans,DAE_KMeans,DCAE_KMeans,PCA_Agglom,DAE_Agglom,DCAE_Agglom,PCA_Spectral,DAE_Spectral,DCAE_Spectral
0,0.844422,1,3,1,0,3,2,3,3,3
1,0.420572,2,2,3,3,2,0,3,0,3
2,0.511275,1,1,2,0,1,3,3,0,3
3,0.783799,1,3,1,0,3,2,3,3,3
4,0.476597,1,1,2,0,1,0,3,0,3
...,...,...,...,...,...,...,...,...,...,...
99995,0.420773,2,2,3,3,2,0,3,0,3
99996,0.116985,0,0,0,1,0,1,0,1,1
99997,0.514981,1,1,2,0,1,3,3,0,3
99998,0.053809,0,0,0,1,0,1,1,2,2
99999,0.256637,0,0,0,1,0,1,0,0,0

In [118]:
def knn_ff_method(method):
    X_train, X_test, y_train, y_test = train_test_split(df[0].values.reshape(-1, 1), df[method], test_size=0.1, random_state = 1)

    knn_clf=KNeighborsClassifier()
    knn_clf.fit(X_train,y_train)
    ypred=knn_clf.predict(X_test)

    result = confusion_matrix(y_test, ypred)
    print("Confusion Matrix:")
    print(result)
    report = classification_report(y_test, ypred)
    print("Report:",)
    print (report)
    acc = accuracy_score(y_test,ypred)
    print("Accuracy:",acc)

In [119]:
knn_ff_method('PCA_KMeans')

Confusion Matrix:
[[3954    0   23   47]
 [   1 5492   32    3]
 [  23   63  160   22]
 [  84    4   48   44]]
Report:
              precision    recall  f1-score   support

           0       0.97      0.98      0.98      4024
           1       0.99      0.99      0.99      5528
           2       0.61      0.60      0.60       268
           3       0.38      0.24      0.30       180

    accuracy                           0.96     10000
   macro avg       0.74      0.70      0.72     10000
weighted avg       0.96      0.96      0.96     10000

Accuracy: 0.965

In [122]:
knn_ff_method('DAE_KMeans')

Confusion Matrix:
[[3914    0   87    0]
 [   0 1375   48   65]
 [  87   39  624    0]
 [   0   79    0 3682]]
Report:
              precision    recall  f1-score   support

           0       0.98      0.98      0.98      4001
           1       0.92      0.92      0.92      1488
           2       0.82      0.83      0.83       750
           3       0.98      0.98      0.98      3761

    accuracy                           0.96     10000
   macro avg       0.93      0.93      0.93     10000
weighted avg       0.96      0.96      0.96     10000

Accuracy: 0.9595

In [123]:
knn_ff_method('DCAE_KMeans')

Confusion Matrix:
[[4015    0    0   83]
 [   0 3158   85    0]
 [   0  101 2064   46]
 [  69    0   37  342]]
Report:
              precision    recall  f1-score   support

           0       0.98      0.98      0.98      4098
           1       0.97      0.97      0.97      3243
           2       0.94      0.93      0.94      2211
           3       0.73      0.76      0.74       448

    accuracy                           0.96     10000
   macro avg       0.91      0.91      0.91     10000
weighted avg       0.96      0.96      0.96     10000

Accuracy: 0.9579

In [120]:
knn_ff_method('PCA_Agglom')

Confusion Matrix:
[[5595    2    3   30]
 [   0 3990   49   14]
 [  15   83   63   20]
 [  46   26   25   39]]
Report:
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      5630
           1       0.97      0.98      0.98      4053
           2       0.45      0.35      0.39       181
           3       0.38      0.29      0.33       136

    accuracy                           0.97     10000
   macro avg       0.70      0.65      0.67     10000
weighted avg       0.96      0.97      0.97     10000

Accuracy: 0.9687

In [124]:
knn_ff_method('DAE_Agglom')

Confusion Matrix:
[[4020    0   82    0]
 [   0 2054   46   90]
 [  80   43  497    0]
 [   0   78    0 3010]]
Report:
              precision    recall  f1-score   support

           0       0.98      0.98      0.98      4102
           1       0.94      0.94      0.94      2190
           2       0.80      0.80      0.80       620
           3       0.97      0.97      0.97      3088

    accuracy                           0.96     10000
   macro avg       0.92      0.92      0.92     10000
weighted avg       0.96      0.96      0.96     10000

Accuracy: 0.9581

In [125]:
knn_ff_method('DCAE_Agglom')

Confusion Matrix:
[[ 572   79    0   44]
 [  80 4000    0    0]
 [   0    0 3280   87]
 [  53    0   83 1722]]
Report:
              precision    recall  f1-score   support

           0       0.81      0.82      0.82       695
           1       0.98      0.98      0.98      4080
           2       0.98      0.97      0.97      3367
           3       0.93      0.93      0.93      1858

    accuracy                           0.96     10000
   macro avg       0.92      0.93      0.93     10000
weighted avg       0.96      0.96      0.96     10000

Accuracy: 0.9574

In [121]:
knn_ff_method('PCA_Spectral')

Confusion Matrix:
[[3320   22    7  110]
 [  75   11    3    0]
 [  26   14    8    0]
 [ 108    0    0 6296]]
Report:
              precision    recall  f1-score   support

           0       0.94      0.96      0.95      3459
           1       0.23      0.12      0.16        89
           2       0.44      0.17      0.24        48
           3       0.98      0.98      0.98      6404

    accuracy                           0.96     10000
   macro avg       0.65      0.56      0.58     10000
weighted avg       0.96      0.96      0.96     10000

Accuracy: 0.9635

In [126]:
knn_ff_method('DAE_Spectral')

Confusion Matrix:
[[3845  202    7   95]
 [ 175 2289   37    0]
 [   1   85   51    0]
 [  92    0    0 3121]]
Report:
              precision    recall  f1-score   support

           0       0.93      0.93      0.93      4149
           1       0.89      0.92      0.90      2501
           2       0.54      0.37      0.44       137
           3       0.97      0.97      0.97      3213

    accuracy                           0.93     10000
   macro avg       0.83      0.80      0.81     10000
weighted avg       0.93      0.93      0.93     10000

Accuracy: 0.9306

In [127]:
knn_ff_method('DCAE_Spectral')

Confusion Matrix:
[[1683  368   26  118]
 [ 385  615   17    0]
 [  32   54   51    0]
 [ 125    0    1 6525]]
Report:
              precision    recall  f1-score   support

           0       0.76      0.77      0.76      2195
           1       0.59      0.60      0.60      1017
           2       0.54      0.37      0.44       137
           3       0.98      0.98      0.98      6651

    accuracy                           0.89     10000
   macro avg       0.72      0.68      0.70     10000
weighted avg       0.89      0.89      0.89     10000

Accuracy: 0.8874